---

- name: Get VPC Cluster workers subnets
  ec2_vpc_subnet_facts:
    region: "{{ aws_region }}"
    filters: 
      "tag:Name": "{{ item.zone_name }}.{{ cluster_name }}"
      "tag:KubernetesCluster": "{{ cluster_name }}"
  with_items: "{{ cluster_zones }}"
  register: subnet_facts

- name: Get VPC Cluster utility subnets
  ec2_vpc_subnet_facts:
    region: "{{ aws_region }}"
    filters: 
      "tag:Name": "utility-{{ item.zone_name }}.{{ cluster_name }}"
      "tag:KubernetesCluster": "{{ cluster_name }}"
  with_items: "{{ cluster_zones }}"
  register: utility_subnet_facts

- name: Cluster subnets
  debug: 
    msg: "{{ subnet_facts.results|map(attribute='subnets.0.id')|list }}"

- name: Gather kubernetes workers security groups
  ec2_group_facts:
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "nodes.{{ cluster_name }}"
  register: workers_sg_facts

- name: Workers security groups
  debug:
    msg: "{{ workers_sg_facts.security_groups|map(attribute='group_id')|list }}"

- name: Get cluster VPC-ID
  set_fact:
    cluster_vpc_id: "{{ subnet_facts.results.0.subnets.0.vpc_id }}"

- name: Debug cluster_vpc_id
  debug:
    msg: "{{ cluster_vpc_id }}"

- name: Get Cluster Route Tables
  ec2_vpc_route_table_facts:
    region: "{{ aws_region }}"
    filters:
      vpc-id: "{{ cluster_vpc_id }}"
  register: cluster_route_tables
