---
###########################
# Setup Kubernetes Cluster
###########################

# NOTICE:
# You Must specify profile name as an extra var (--extra-vars "profile=XXXX") 

- hosts: localhost
  connection: local
  gather_facts: True

  vars_files:
    - "{{ lookup('env', 'PROFILES_PATH') or '../profiles' }}/{{ profile }}.yml"

  pre_tasks:
    - name: Download secrets from S3
      aws_s3:
        bucket: "{{ secrets_bucket }}"
        object: "vault/{{ profile }}"
        dest: "{{ secrets_file }}"
        mode: get

    - name: "Gather AWS ACM facts in {{ aws_region }}"
      aws_acm_facts:
        region: "{{ aws_region }}"
        statuses:
        - ISSUED
      register: acm_check

    - name: Set facts for the AWS ACM
      set_fact:
          # acm_type: "{{ acm_check.certificates[0].type }}"
          acm_cert: "{{ acm_check.certificates[0].certificate_arn }}"

    - name: Validate profile yaml-file
      validator:
        source: "{{ lookup('env', 'PROFILES_PATH') or '../profiles' }}/{{ profile }}.yml"
        template: "{{ lookup('env', 'PROFILE_TEMPLATE_PATH') or '../profiles' }}/profiles_template.yaml"

    - name: Include vars
      include_vars:
        file: "{{ secrets_file }}"

    - name: Validate secret yaml-file
      validator:
        source: "{{ vars }}"
        template: "{{ lookup('env', 'PROFILE_TEMPLATE_PATH') or '../profiles' }}/secrets_template.yaml"

  post_tasks:
    - name: Delete secrets file
      file:
        name: "{{ secrets_file }}"
        state: absent

  roles:
    - k8s_create_cluster
    - helm
    - certificates
    - aws_resources
    - k8s_resources
