apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-dag-filler"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-dag-filler"
spec:
  template:
    spec:
      containers:
      - name: dag-filler
        image: "{{ .Values.image }}"
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
        env:
        - name: POSTGRES_HOST
        {{- if .Values.postgres.external}}
          value: "{{ .Values.postgres.host }}"
        {{- else }}
          value: "{{ .Release.Name }}-postgres"
        {{- end }}
        - name: POSTGRES_PORT
          value: "{{ .Values.postgres.port }}"
        - name: AIRFLOW_HOME
          value: "/home/airflow"
        - name: BOOTUP_DIRECTORY
          value: "/opt/bootup"
        - name: SECRETS_DIRECTORY
          value: "/opt/secrets"
        command: ["/bin/sh","-c"]
        args: ["airflow delete_dag {{ .Values.example_dag_id }} -y || true; cp -R /mnt/dags/. {{ .Values.storage.airflow_dags_directory }}"]
        volumeMounts:
        - name: connections-config
          mountPath: /opt/secrets
        - name: dag-volume
          mountPath: "{{ .Values.storage.airflow_dags_directory }}"
        - name: airflow-dags-source
          mountPath: /mnt/dags
      restartPolicy: Never
      volumes:
      - name: connections-config
        secret:
          secretName: "{{ .Release.Name }}-connections-config"
      - name: dag-volume
        persistentVolumeClaim:
          {{- if .Values.storage.use_specified_pvc }}
          claimName: {{ .Values.storage.pvc_name }}
          {{- else}}
          claimName: "{{ .Release.Name }}-dag-pvc"
          {{- end}}
      - name: airflow-dags-source
        configMap:
          name: "{{ .Release.Name }}-dags"