kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-dags"
data:
  example_python_work.py: |-
    # -*- coding: utf-8 -*-
    import datetime
    import logging

    import airflow
    from airflow.operators.bash_operator import BashOperator
    from airflow.operators.python_operator import PythonOperator
    from airflow.models import DAG

    args = {
        'owner': 'airflow',
        'start_date': datetime.datetime.utcnow() - datetime.timedelta(hours=1)
    }

    dag = DAG(
        dag_id='example_python_work', default_args=args,
        schedule_interval='@once',
        dagrun_timeout=datetime.timedelta(minutes=2))
    
    executor_config = {
        "KubernetesExecutor": {
        "image": "{{ .Values.image }}",
        "annotations": { "iam.amazonaws.com/role": "{{ .Values.clusterName }}-{{ .Values.enclave }}-airflow-role" }
        }
    }

    echo_1 = BashOperator(task_id='echo_1',
                          bash_command='env',
                          dag=dag,
                          executor_config=executor_config
    )

    echo_2 = BashOperator(task_id='echo_2',
                          bash_command='ls -lsa',
                          dag=dag,
                          executor_config=executor_config
    )
