kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "{{ .Release.Name }}-worker"
rules:
- apiGroups: [""] # core API group
  resources: ["configmaps"]
  verbs: ["list", "create", "get", "patch", "update"]
- apiGroups: [""] # core API group
  resources: ["secrets"]
  verbs: ["watch", "get"]
  resourceNames: ['airflow-credentials']
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "{{ .Release.Name }}-worker"
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: "{{ .Release.Name }}-worker"
roleRef:
  kind: Role
  name: "{{ .Release.Name }}-worker"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-worker"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-scheduler"
  namespace: {{ .Release.Namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "{{ .Release.Name }}-scheduler"
rules:
- apiGroups: [""] # core API group
  resources: ["configmaps"]
  verbs: ["list", "get"]
- apiGroups: [""] # core API group
  resources: ["secrets"]
  verbs: ["watch", "get"]
  resourceNames: ['airflow-credentials']
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] 
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-scheduler"
subjects:
  - kind: ServiceAccount
    name:  "{{ .Release.Name }}-scheduler"
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: "{{ .Release.Name }}-scheduler"
apiGroup: rbac.authorization.k8s.io