apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-vars-filler"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-vars-filler"
spec:
  template:
    spec:
      containers:
      - name: vars-filler
        image: "{{ .Values.image }}"
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
        env:
        - name: POSTGRES_HOST
        {{- if .Values.postgres.external}}
          value: "{{ .Values.postgres.host }}"
        {{- else }}
          value: "{{ .Release.Name }}-postgres"
        {{- end }}
        - name: POSTGRES_PORT
          value: "{{ .Values.postgres.port }}"
        - name: AIRFLOW_HOME
          value: "/home/airflow"
        - name: BOOTUP_DIRECTORY
          value: "/opt/bootup"
        - name: SECRETS_DIRECTORY
          value: "/opt/secrets"
        command: ["/bin/sh","-c"]
        args: ["airflow variables --set CLUSTER_NAME {{ .Values.clusterName }} && airflow variables --set NAMESPACE {{ .Values.enclave }} && airflow variables --set S3_BUCKET_NAME {{ .Values.storage.s3_root_path }}"]
        volumeMounts:
        - name: airflow-config
          mountPath: /home/airflow/airflow.cfg
          subPath: airflow.cfg
        - name: connections-config
          mountPath: /opt/secrets
        - name: airflow-dags
          mountPath: "{{ .Values.storage.airflow_dags_directory }}"
      volumes:
      - name: airflow-config
        configMap:
          name: "{{ .Release.Name }}-config"
      - name: connections-config
        secret:
          secretName: "{{ .Release.Name }}-connections-config"
      - name: airflow-dags
        persistentVolumeClaim:
          {{- if .Values.storage.use_specified_pvc }}
          claimName: {{ .Values.storage.pvc_name }}
          {{- else}}
          claimName: "{{ .Release.Name }}-dag-pvc"
          {{- end}}
      restartPolicy: Never
