---
#######################
# Delete AWS resources
#######################

# Delete Airflow RDS 
- name: Get RDS instance status
  shell: "aws --region {{ aws_region }} rds  describe-db-instances --db-instance-identifier {{ env_name }}-airflow-rds"
  register: rds_instance_status
  changed_when: "rds_instance_status.rc != 255"
  ignore_errors: true

- name: Delete Airflow RDS instance
  rds:
    command: delete
    instance_name: "{{ env_name }}-airflow-rds"
    region: "{{ aws_region }}"
    wait: yes
    wait_timeout: 600
  when: rds_instance_status.changed

- name: Ensure RDS instance is deleted
  pause:
    seconds: 5
  when: rds_instance_status.changed

- name: Delete Airflow RDS subnet group
  rds_subnet_group:
    name: "{{env_name}}-airflow-rds-subnets"
    state: absent
    region: "{{ aws_region }}"

- name: Delete Airflow RDS Security Group
  ec2_group:
    region: "{{ aws_region }}"
    name: "{{env_name}}-airflow-rds-sg"
    state: absent

# Delete Airflow EFS
- name: Delete Airflow EFS
  efs:
    state: absent
    name:  "{{env_name}}-airflow-efs"
    region: "{{ aws_region }}"

- name: Ensure EFS is deleted
  pause:
    seconds: 5

- name: Delete Airflow EFS Security Group
  ec2_group:
    region: "{{ aws_region }}"
    name: "{{env_name}}-airflow-efs-sg"
    state: absent

- name: Get cluster VPC peers
  ec2_vpc_peering_facts:
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ cluster_name }}"
      "tag:KubernetesCluster": "{{ cluster_name }}"
      status-code: ['active']
  register: cluster_vpc_peers

- name: List of VPC peers to be deleted
  debug:
    msg: "About to delete VPC peer {{ item }}"
  with_items: "{{ cluster_vpc_peers.result | map(attribute='vpc_peering_connection_id')|list }}"

- name: Delete VPC Peer
  ec2_vpc_peer:
    region: "{{ aws_region }}"
    peering_id: "{{ item }}"
    state: absent
  register: vpc_peer
  with_items: "{{ cluster_vpc_peers.result | map(attribute='vpc_peering_connection_id')|list }}"
