---

- set_fact:
    tmp_values_file: "{{ tmp_dir }}/legion-core-values.{{ cluster_name }}.yaml"

- name: Create legion configuration (values) file
  template:
    src: legion-core-values.yaml.j2
    dest: "{{ tmp_values_file }}"
    mode: 0777

- name: Install legion core helm chart
  include_role:
    name: deploy_helm_chart
  vars:
    release_name: legion-core
    values_file: "{{ tmp_values_file }}"
    namespace: default
    src_chart_name: legion-core
    chart_name: legion-helm/legion-core
    chart_version: "{{ legion_version }}"

- name: Label default namespace with legion-component=core
  shell: kubectl --context {{ cluster_name }} label ns default legion-component=core --overwrite