kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "model"
rules:
- apiGroups: [""] # core API group
  resources: ["configmaps", "secrets"]
  verbs: ["watch", "get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "model"
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: "model"
roleRef:
  kind: Role
  name: "model"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "model"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "model-builder"
rules:
- apiGroups: [""] # core API group
  resources: ["pods"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "model-builder"
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: "model-builder"
roleRef:
  kind: Role
  name: "model-builder"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "model-builder"