---

- name: Create EFS provisioner
  template:
    src: provisioner.yaml.j2
    dest: "{{ tmp_dir }}/provisioner.yaml.{{ cluster_name }}.j2"
    mode: 0644

- name: Create NFS persistance provisioner
  command: "kubectl --context {{ cluster_name }} apply -f {{ tmp_dir }}/provisioner.yaml.{{ cluster_name }}.j2"
