# Should be configured due installation
rootDomain: k8s-nightly.epm.kharlamov.biz

# Default values may be used
rbac: true

dockerHubGroup: "legion"
pypiServer: ""
version: "latest"

auth:
  enabled: false
  annotations: {}

connections:
  docker:
    type: proxy
    url: ~
    user: ~
    password: ~

grafana:
  adminUser: admin_user
  adminPassword: admin_password
  fullnameOverride: "legion-core-grafana"
  extraConfigmapMounts:
    - name: grafana-model-build-js
      configMap: grafana-model-build-js
      mountPath: /usr/share/grafana/public/dashboards
      readOnly: true
  resources:
    limits:
      cpu: 512m
      memory: 512Mi
    requests:
      cpu: 256m
      memory: 256Mi
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
  persistence:
    enabled: true
    initChownData: true
    storageClassName: gp2
    accessModes:
    - ReadWriteOnce
    size: 10Gi
  service:
    labels:
      legion.component: grafana
  ingress:
    enabled: true
    hosts:
    - "grafana.k8s-nightly.epm.kharlamov.biz"
    - "grafana.local.grafana.k8s-nightly.epm.kharlamov.biz"
    tls:
    - secretName: "k8s-nightly.epm.kharlamov.biz-tls"
      hosts: ["grafana.k8s-nightly.epm.kharlamov.biz"]
    annotations:
      nginx.ingress.kubernetes.io/auth-signin: "https://auth.legion.epm.org/oauth2/start?rd=https://$host$request_uri$is_args$args"
      nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.kube-system.svc.cluster.local:4180/oauth2/auth"
  env:
    GF_AUTH_ANONYMOUS_ENABLED: "true"
  setup:
    image:
      repository: legion/k8s-ansible
      tag: latest


graphite:
  enabled: true
  url: "http://legion-core-graphite.default.svc.cluster.local:80"
  image:
    repository: "hopsoft/graphite-statsd"
    tag: "v0.9.15-phusion0.9.18@sha256:b4d170e1c31b7474adb5e91fa789e50bb15f003fe6e6717393a597142815efdd"

