apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: edge-exporter
    monitoring: prometheus
  name: edge-exporter
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - "{{ .Values.namespace }}"
  selector:
    matchLabels:
      component: "{{ .Release.Name }}-edge"