{{ if .Values.edi.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-cluster-secrets"
type: Opaque
data:
  grafana.user: "{{ .Values.grafana.adminUser | b64enc }}"
  grafana.password: "{{ .Values.grafana.adminPassword | b64enc }}"
  docker.user: "{{ .Values.connections.docker.user | b64enc }}"
  docker.password: "{{ .Values.connections.docker.password | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-jwt-config"
type: Opaque
data:
  jwt.secret: "{{ .Values.secrets.token_secret | b64enc }}"
  jwt.length.minutes: "{{ .Values.secrets.token_ttl_minutes | b64enc }}"
  jwt.max.length.minutes: "{{ .Values.secrets.max_token_ttl_minutes | b64enc }}"
  jwt.exp.datetime: "{{ .Values.secrets.token_exp_datetime | b64enc }}"
{{- end }}

