apiVersion: v1
kind: Service
metadata:
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ template "dex.fullname" . }}
  labels:
    app: {{ template "dex.name" . }}
    chart: {{ template "dex.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
{{- if .Values.tls.secret_mode }}{{- else }}
    - port: 80
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
{{- end }}
  selector:
    app: {{ template "dex.name" . }}
    release: {{ .Release.Name }}
