apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: model-deployments.legion-platform.org
spec:
  group: legion-platform.org
  version: v1
  scope: Namespaced
  names:
    plural: model-deployments
    singular: model-deployment
    kind: ModelDeployment
    shortNames:
    - md
    categories:
    - all
    - serving
    - legion
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            image:
              type: string
            replicas:
              type: integer
              minimum: 1
  additionalPrinterColumns:
    - name: Model Image
      type: string
      JSONPath: .spec.image
    - name: Desired replicas
      type: integet
      JSONPath: .spec.replicas
#    - name: Ready
#      type: string
#      JSONPath: ".status.conditions[?(@.type==\"Ready\")].status"
#    - name: Reason
#      type: string
#      JSONPath: ".status.conditions[?(@.type==\"Ready\")].reason"